frase = ('Aprendendo programar em python')
#print (len(frase)
print (frase[:30])
print (frase[::15])
print (frase.count('n'))
print ('programar' in frase)
#print (frase.replace ('em', 'com'))
frase = frase.replace ('em', 'com')
print (frase)
print (frase.split())
