des = ('Desafio-009 tabuada')
print ('{}.'.format(des))
#Desafio-09 >>> Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada.

num = int(input('Digite um número: '))

a1 = (num*0)
a2 = (num*1)
a3 = (num*2)
a4 = (num*3)
a5 = (num*4)
a6 = (num*5)
a7 = (num*6)
a8 = (num*7)
a9 = (num*8)
a10 = (num*9)
a11 = (num*10)

print ('A tabuada de {} é:'.format(num))
print (num, 'x 0 = {}'.format(a1))
print (num, 'x 1 = {}'.format(a2))
print (num, 'x 2 = {}'.format(a3))
print (num, 'x 3 = {}'.format(a4))
print (num, 'x 4 = {}'.format(a5))
print (num, 'x 5 = {}'.format(a6))
print (num, 'x 6 = {}'.format(a7))
print (num, 'x 7 = {}'.format(a8))
print (num, 'x 8 = {}'.format(a9))
print (num, 'x 9 = {}'.format(a10))
print (num, 'x 10 = {}'.format(a11))

print ('The End')
